import "@/styles/globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Inter } from "next/font/google";
import { ClerkProvider, ClerkLoaded } from "@clerk/nextjs"

import { TRPCReactProvider } from "@/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={`font-sans ${inter.variable} flex flex-col min-h-screen`}>
          <ClerkLoaded>
            <Header />
            <TRPCReactProvider>{children}</TRPCReactProvider>
            <Footer />
          </ClerkLoaded>
        </body>
      </ClerkProvider>
    </html>
  );
}
